os:
    - Visual Studio 2015
environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
clone_folder: C:\mc_analyzer
platform:
    - x86
configuration:
    - Release
build_script:
    - git submodule update --init --recursive
    - cmake . -Bbuild
    - cmake --build build --config Release
test_script:
    - cd build
    - ctest --build-config Release --output-on-failure