dist: bionic
sudo: require

language: cpp
compiler: gcc

#compiler:
#  - clang
#  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libboost-all-dev
      

script:
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - gcc -v
    - g++ -v
    - /usr/local/bin/g++ -v
    - cmake --version
    - git clone 'https://github.com/ddemidov/amgcl.git' '../amgcl/'
    - ls ..
    - mkdir cmake-build
    - cd cmake-build
    - echo Create Project...
    - cmake -DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
    - echo Build Project...
    - cmake --build .
    - /usr/local/bin/g++   -I/home/travis/build/Necktschnagge/markov_chain_analyzer/../amgcl -I/home/travis/build/Necktschnagge/markov_chain_analyzer/cmake-build  -std=c++17 -o CMakeFiles/MC_Analyzer.dir/main.cpp.o -c /home/travis/build/Necktschnagge/markov_chain_analyzer/main.cpp

    